POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFzd2Fuc29uIiwiaWQiOiI1ZTFjOWQxNDZiOGE2OTMyMDAwNGFhMGIiLCJpYXQiOjE1NzkwOTUyOTF9.EBtR3FMNRlsHdV9fKeHzfQe1jBftGafauLrbrgKRMUI

{
    "title": "This is How It's Going to Work",
    "author": "Drew Magary",
    "url": "https://drewmagary.kinja.com/this-is-how-it-s-gonna-work-1839505029",
    "likes": 2581
}