PUT http://localhost:3003/api/blogs/5e171ed3347f6237e05b3aa6
Content-Type: application/json

{
    "title": "How An Inner-City Minnesota High School Built a Girls’ Badminton Dynasty",
    "author": "Sarah Barker",
    "url": "https://deadspin.com/how-an-inner-city-minnesota-high-school-built-a-girls-1825873078",
    "likes": 9999
}